#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
FRONTEND_DIR="${FRONTEND_DIR:-$PROJECT_ROOT/frontend}"
ENV_FILE="$FRONTEND_DIR/.env"

if [ -f "$ENV_FILE" ]; then
  echo "[start_frontend] Loading environment from $ENV_FILE"
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
else
  echo "[start_frontend] No .env found, using process environment"
fi

PORT="${FRONTEND_PORT:-8000}"
BIND_HOST="${FRONTEND_HOST:-0.0.0.0}"

if [ ! -d "$FRONTEND_DIR" ]; then
  echo "[start_frontend] FRONTEND_DIR=$FRONTEND_DIR not found" >&2
  exit 1
fi

# Generate config.js from env
CONFIG_JS="$FRONTEND_DIR/config.js"
echo "[start_frontend] Generating $CONFIG_JS from environment"
STREAM_URL_VAL="${STREAM_URL:-rtmp://localhost/live}"
RELAY_WS_URL_VAL="${RELAY_WS_URL:-ws://localhost:9000/subtitles}"

# When the page is served over HTTPS, browsers will block http:// and ws:// as mixed content.
# Auto-upgrade defaults (and common env values) to secure schemes.
STREAM_URL_VAL="${STREAM_URL_VAL/http:\/\//https:\/\/}"
RELAY_WS_URL_VAL="${RELAY_WS_URL_VAL/ws:\/\//wss:\/\/}"
cat >"$CONFIG_JS" <<EOF
// Auto-generated by start_frontend.sh. Edit frontend/config.js to override.
window.FRONTEND_CONFIG = {
  streamUrl: "$STREAM_URL_VAL",
  relayWsUrl: "$RELAY_WS_URL_VAL"
};
EOF

cd "$FRONTEND_DIR"

CERT_FILE="${SSL_CERT_FILE:-$PROJECT_ROOT/ssl-config/cert.pem}"
KEY_FILE="${SSL_KEY_FILE:-$PROJECT_ROOT/ssl-config/key.pem}"

if [ ! -f "$CERT_FILE" ]; then
  echo "[start_frontend] Missing cert: $CERT_FILE" >&2
  exit 1
fi
if [ ! -f "$KEY_FILE" ]; then
  echo "[start_frontend] Missing key: $KEY_FILE" >&2
  exit 1
fi

echo "[start_frontend] Serving $FRONTEND_DIR at https://${BIND_HOST}:${PORT}"
PYTHON_CMD="${PYTHON_CMD:-python3}"
exec "$PYTHON_CMD" ./serve_https.py --port "${PORT}" --bind "${BIND_HOST}" --cert "${CERT_FILE}" --key "${KEY_FILE}" "$@"

